import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";

import { MainProvider } from "@/app/pageContext/page";
import SideBar from "@/components/sideBar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${geistMono.variable} ${geistSans.variable}`}>
      <body>
        <AuthProvider>
          <MainProvider>
            <div className="flex h-screen bg-gray-50">
              <SideBar />
              <main className="flex-1 overflow-y-auto p-8">
                {children} 
              </main>
            </div>
          </MainProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
